### ISSUE TITLE
v8.2.0: Release Plan

### ISSUE THREAD

**Issue by AndreasBackx** [pallets/click#2789]
_This release follows and is worked on together with the [8.1.8 Release Plan](https://github.com/pallets/click/issues/2793)._

This summarises the work still needing to be done for 8.2.0, particularly on the PRs and issues attached to the milestone. The summary is based on the comments and additionally some of my own thoughts. This is an attempt to make the `8.2.0` changes easier to review as there has been a lack of time by contributors. This was following a brief discussion on Discord where I asked what can be done to help contribute even though there is a lack of time by the contributors themselves:
> Coming up with a list of “here’s bug fixes PRs that work, merge the and make a fix release” could be helpful as well

# Pull Requests & Issues

- [x] #605 could be resolved by either
	- ~~#2210~~
	  - ~~Document `EnumChoice`~~
	  - I propose we leave the aliasing functionality out of the implementation for now. It can be added and discussed in a separate issue.
  - [x] #2796
- [x] #2263
	- [x] #2271
	  - [x] _Better title: add `deprecated` to `Option`._
	  - [x] This does not add `deprecated` to `Parameter` so it is not available to `@click.argument`.
	  - [x] Align deprecation implementation between it and `Command(deprecated: bool)` implementation.
	  - [x] Make it print a deprecated messaged on use.
	- [x] Move `deprecated` to `Parameter` so both `Option` and `Argument` support it.
- [x] #2365
  - It's ignoring a type error that might be preventable if `param.param_type_name == "option"` were to be replaced with `isinstance(param, Option)`. However, that will introduce a circular dependency. I'm not sure it's something that's easily fixable right now.
- [x] #2397
  - The current implementation checks every single time an option is used, whether its name has been used before. I feel like we can move this check elsewhere so it only does this check once per command. If you want to be technical about it, it should make the check O(n) instead of O(n^2) where n is the number of options.
    - [x] Move duplicate option declaration check so it only runs once per command instead of once per option.
  - [x] Document that a `UserWarning` will be logged if an "option" declaration is reused.
  - [x] ~~Nit: the warnings import should be moved to the module level.~~
- [x] #2501 can simply be closed because it was fixing #2500 which was resolved by #2724.
- [x] #2509
  - Already reviewed and ready to go, waiting to be merged.
- [x] #2517
  - [x] ~~Document `Option.get_help_extra`~~ Let's not make it entirely public for now.
  - I'm personally not the biggest fan of the untyped implementation. I think it should be typed so it's clear what "extra items" are supported.
    - [x] Revamp implementation of `get_help_extra` to add typing instead of relying on untyped dict.
- [x] #2523
  - Good to go, seems agreed upon.
- [x] #2696
  - Good to go.
- [x] #2680
  - Well tested as well.
  - Perhaps the `ctx.call_on_close` documentation should mention the change in behaviour as well? Though I would say it's assumed that an exit actually would call this too and it's not needed.
- [x] #2727
  - Before this PR `ProgressBar.is_hidden` existed. This adds `ProgressBar.hidden` which is the value of the new passed constructor field `hidden`. This was mentioned in the comments as well but then the author faced issues getting it to work in tests. I'm sure we can get this to work however, if not, then we can at least document why it's there.
    - [x] Merge `ProgressBar._is_hidden` and `ProgressBar.hidden` into `ProgressBar.is_hidden`.

## Potentially Included

_These are primarily added in this separate section as I classified them as 8.2.0 though haven't necessarily been "agreed upon" by others (yet)._

- [x] #2788 flags enabled with `envvar` will return the `flag_value` if set.
- [x] #2775
	- Seems good to go, I don't think we should update the utilities documentation for this as they seem like implementation details that shouldn't matter?
- ~~#1572 might be made easier if rebased on #2775. I said they can rebase on #2775 and already start any work as we're aiming to get #2775 in 8.2.0.~~
- ~~#2681~~
	- Needs checklist completion (tests, changes, etc.)
- [x] #2663
- [x] #2622
	- [x] Needs checklist completion (tests, changes, etc.)
- [x] #1489
	- [x] ~~Might need a documentation change.~~
- [x] #2068
	- Needed some changes to keep `filename` and not introduce `filenames`.
- [x] #2767
	- Fixed in #2800
- [x] #2630 

# Next steps

I propose the following:
1. A contributor with the necessary power to merge all of these PRs into either `main` or another temporary branch, the latter being preferred imo.
2. I will follow up and address all of the openstanding issues highlighted above. Each will be done in a PR and can be commented on further there.
3. Once the openstanding (and other issues that arose during their "fixing") are merged, 8.2.0 can be released.
    * Almost all of these PRs have a good amount of tests that should prevent any low hanging issues from rearing their heads.

This assumes we do not add any more items to 8.2.0 so we can keep it manageable for now.

Let me know if this sounds like a good idea. I'm also available on Discord.

**Comment by kdeldycke** [comment]
I just tried to use the `main` branch to test the upcoming 8.2.0 release, but it seems that my PR https://github.com/pallets/click/pull/2811 , while present in 8.1.8 (see: https://github.com/pallets/click/commit/70c673d37eb91ba42a129be9037caf3ebed62f3e ), has not been merged into `main`.

Should I consider `main` as not being a follow-up on 8.1.8?

**Comment by kdeldycke** [comment]
Looking at the different branches, it seems that the last time `stable` was merged into `main` is Nov 5, 2024 (see: https://github.com/pallets/click/commit/d791537317947448a3960662d00acf160eff2602). All changed in `stable` from Nov 5, 2024 to today have not reached the `main` branch yet.

There was an attempt in https://github.com/pallets/click/pull/2830 but it has not been updated since Dec 24, 2024, and so lacks changes both from `stable` and `main` that were pushed after the 8.1.8 release.

Is there a plan to reconcile `stable` and `main` so I can test the upcoming 8.2.0 before its release?

**Comment by kdeldycke** [comment]
So all in all, what's missing in `main` is this changeset: https://github.com/pallets/click/compare/26aa7bf3189e19a8a63890b1c2cc7eca24312d6f...stable

**Comment by kdeldycke** [comment]
I finally fixed all conflicts in #2873. This should help the release of 8.2.0.

**Comment by webknjaz** [comment]
Might be worth including a fix for #2877.
